#!/bin/sh

echo "Test 1: Not enough arguments" 1>&2
./test
echo

echo "Test 2: Invalid first image" 1>&2 
./test "fake.png" "fake2.png"
echo

echo "Test 3: Invalid second image" 1>&2
./test $1 "fake3.png"
echo

echo "Test 4: Differing dimensions between the two images" 1>&2
./test $1 $4
echo

echo "Test 5: Images are identical"
./test $1 $2
echo

echo "Test 6: Images are different"
./test $1 $3
echo
